PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT
distinct ?envo_class ?envo_id ?label
WHERE {
    ?envo_class a owl:Class .
    optional {
        ?envo_class rdfs:label ?label
    }
    filter(strstarts(str(?envo_class), "http://purl.obolibrary.org/obo/ENVO"))
    bind(replace(str(?envo_class), "http://purl.obolibrary.org/obo/ENVO_", "") as ?envo_id)
}
order by ?envo_class
